export class UserAffidavit {
    status: string;
    userid: number;
    userAffidavitId: number;
    templateName: string;
    templateVersionId: string;
    price: number;
    userAffidavitCustomName: string;
    htmlValue: string;
    cssvalue: any;
    registrarStatus: string;
    registrarId: number;
    registrarName: string;
    registrarCourtName: string;
    flutterwaveRef: string;
    transactionRef: string;
	affidavitPrice: number;
    chargedamount: number;
    disablePreviewFlag:boolean;
    isUploaded:boolean;
    deponentId:number;
    meetingTiming: string;
    meetingEndTiming: string;
    missedAppointment: boolean;
    canCancelAppointment: boolean;
    isExpress: boolean;
    templateFastTrackPrice: number;
    templatePrice: number;
    isCaseRelated:boolean;
    signatureStatus: string;
    signatureDocumentId: string;
    storedDocumentAvailable: boolean;
    registrarComments: string;
    signatureRejectedAt: string;
    signatureRejectedByRole: string;
    signatureUserSignedAt: string;
    disableSendToSign: boolean;
    appointmentId: number;
    attendeeId: number;
    appointmentJoinUrl: string;
    appointmentCancelled: boolean;
    appointmentCompleted: boolean;
    canRecreate: boolean;
    recreateUntil: string;
    creationMethod: string;
}
